<h2>Košík</h2>
<?php
    $form_data = $_SESSION["form_data"]["polozka"];
    $response_doprava = ziskat_dopravu();
    $response_platba = ziskat_platbu();

    $cena_celkem = 0;
    foreach ($form_data as $item) {
        $cena_celkem = $item["Cena"] * $item["pocet"];

        echo('
                        <div>
                            <a class="obrazek"  href="produkt?ID_P='.$item["ID_P"].'">
                                <img alt="'.htmlspecialchars($item["Nazev"]).'" src="images/'.$item["Obrazek"].'">
                            </a>
                            <h3>');
        if ($item["pocet"] != 1) {
            echo $item["pocet"].'×';
        }
        echo(' <a class="sede" href="produkt?ID_P='.$item["ID_P"].'" >'.$item["Nazev"].'</a></h3>
                        <div class="cena">
                            '.number_format($item["Cena"] * $item["pocet"], thousands_separator: ' ').' Kč
                        </div>
                        </div>
                        ');

    }
?>
<div class="info-objednavka">
    <div id="doprava-kosik" class="plat_kosik">
        <?php
            if ($response_doprava["checked"]) {
                echo($response_doprava["kosik_html"]);
            }
        ?>
    </div>
    <div id="platba-kosik" class="plat_kosik">
        <?php
            if ($response_platba["checked"]) {
                echo($response_platba["kosik_html"]);
            }
        ?>
    </div>
    <div class="cena-celkem">
        <span>Celkem:</span>
        <span class="strong"><?php echo(number_format($cena_celkem, thousands_separator: ' ').' Kč') ?></span>
    </div>
</div>